export { default as rimacLogo } from './rimac_logo.png'
export { default as rimacNegativeLogo } from './rimac_negative_logo.png'
export { default as rimacNegativeLogoSm } from './rimac_negative_logo_sm.png'
export { default as leftSparkleDesktop } from './left_sparkle_desktop.png'
export { default as rightSparkleDesktop } from './right_sparkle_desktop.png'
export { default as leftSparkleMobile } from './left_sparkle_mobile.png'
export { default as rightSparkleMobile } from './right_sparkle_mobile.png'
